# Ativar mouse
set -g mouse on

# Reduz delay do prefix (melhora ALT/CTRL)
set -s escape-time 0

# Ajuda o tmux a entender teclas modificadas (Ctrl/Alt/Shift + setas)
set -g xterm-keys on

##### NAVEGAÇÃO ENTRE WINDOWS (CTRL + ALT + SETAS) #####
# Navegar para window anterior
bind -n C-M-Left previous-window

# Navegar para próxima window
bind -n C-M-Right next-window


##### NAVEGAÇÃO ENTRE PANES (CTRL + SETAS) #####

bind -n C-Left  select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up    select-pane -U
bind -n C-Down  select-pane -D


##### SPLIT COM ALT + SETAS #####

# ALT + ←  cria split vertical e posiciona à esquerda
bind -n M-Left  split-window -h

# ALT + →  cria split vertical
bind -n M-Right split-window -h

# ALT + ↑  cria split horizontal
bind -n M-Up    split-window -v

# ALT + ↓  cria split horizontal
bind -n M-Down  split-window -v





bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
